name: fuzzyqd2
channels:
  - conda-forge
dependencies:
  # Python
  - python>=3.9
  - numpy>=1.22
  - scipy>=1.10
  - matplotlib>=3.5
  - pymatgen>=2024.0
  - seekpath>=2.1

  # Build toolchain (from conda-forge)
  - compilers
  - cmake>=3.22
  - ninja

  # C++ deps
  - pybind11>=2.12
  - eigen
  - libint>=2.6
  - boost             # <--- ADD BOOST HERE

  - pip

